# Generated by Django 5.1 on 2024-09-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "findout_app",
            "0002_remove_dealer_user_user_dealer_name_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
