# Generated by Django 5.1 on 2024-09-09 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("findout_app", "0003_user_password_reset_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_reset_code",
        ),
    ]
