# Generated by Django 5.1 on 2024-11-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("findout_app", "0007_delete_imageupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
