# Generated by Django 5.1 on 2024-11-13 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("findout_app", "0008_imageupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ImageUpload",
        ),
    ]
